# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 09:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [('nous', '0001_initial'), ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                (
                    'id', models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False
                    )
                ),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                (
                    'id', models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False
                    )
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'media_type', models.CharField(
                        choices=[
                            ('BOOK', 'Book'), ('ARTICLE', 'Article'),
                            ('AUDIO', 'Audio'), ('VIDEO', 'Video'),
                            ('AUDIO_COURSE', 'Audio course'),
                            ('VIDEO_COURSE', 'Video course'),
                            ('OTHER', 'Other')
                        ],
                        default='OTHER',
                        max_length=255
                    )
                ),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('authors', models.ManyToManyField(to='nous.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                (
                    'id', models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False
                    )
                ),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='resource',
            name='topics',
            field=models.ManyToManyField(to='nous.Topic'),
        ),
    ]
