# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 09:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('nous', '0002_auto_20160725_0935'), ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
